### ISSUE TITLE
Error when install the module

### ISSUE THREAD

**Issue by tsobeng** [xcgd/analytic_structure#1]
I have this error when try to install this module:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\http.py", line 530, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\http.py", line 567, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\http.py", line 303, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\http.py", line 300, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\http.py", line 796, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\http.py", line 396, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server\openerp\addons\web\controllers\main.py", line 953, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server\openerp\addons\web\controllers\main.py", line 941, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server\openerp\addons\base\module\module.py", line 450, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server\openerp\addons\base\module\module.py", line 498, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\modules\registry.py", line 366, in new
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\modules\loading.py", line 355, in load_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\modules\loading.py", line 255, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\modules\loading.py", line 152, in load_module_graph
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\modules\registry.py", line 162, in load
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server.\openerp\models.py", line 648, in _build_model
  File "C:\Program Files (x86)\Odoo 8.0-20150226\server\openerp\addons\analytic_structure\analytic_dimension.py", line 36, in __new__
TypeError: 'NoneType' object does not support item assignment

**Comment by houzefa-abba** [comment]
Hey,

The version you are using does not yet work on Odoo 8 (only Odoo 7).

We have already done the Odoo 8 work (and it is working fine) but the code is not up-to-date on github; it is all on bitbucket at https://bitbucket.org/xcg/analytic_structure.
Make sure you use the "odoo8" branch.

This ticket can be closed once the github code has been synchronized with the latest from bitbucket.

**Comment by tsobeng** [comment]
Thank you @houzefa-abba it's working fine!

**Comment by houzefa-abba** [comment]
Good!

There is now an odoo-8 branch here on github as well.
